## 모듈 불러오기

In [4]:
# 데이터분석 
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from numpy import NaN as NA

# 시각화 
plt.rcParams['axes.unicode_minus'] = False
plt.rcParams['font.family'] = 'Malgun Gothic'
# plt.rcParams['font.family'] = 'AppleGothic'
%matplotlib inline 
import seaborn as sns 
sns.set(font="Malgun Gothic", #
        rc={"axes.unicode_minus":False},
        style='whitegrid')

# warning ignore 
import warnings
warnings.filterwarnings('ignore')

# 데이터 불러오기

## 설문결과데이터

In [21]:
res = pd.read_csv('4.체감안전도_통계(2017~2019).csv')
res['large_category'] = res.large_category.str[:6]
res = res[~(res.medium_category.str.contains('\d'))]
res = res[~(res.medium_category.isin(['남자','여자']))]
res = res[~(res.medium_category.isin(['남성','여성']))]
res.medium_category = res.medium_category.str.replace('서$', '')
res.medium_category = res.medium_category + '경찰서'
res.medium_category = res.medium_category.str.replace( '경기남부','')
res.medium_category = res.medium_category.str.replace( '경남','')
res.medium_category = res.medium_category.str.replace( '충남','')
res.rename(columns={'large_category':'year', 'medium_category':'police'}, inplace=True)
res = res[['year', 'police',' rob_satety_q1', 'mur_safety_q2', 'ta_safety_q3', 'raw_odder_q4','overall_q5']]
res.year = res.year.str.replace(' ', '')
res.reset_index(inplace=True, drop=True)
res

,year,police,rob_satety_q1,mur_safety_q2,ta_safety_q3,raw_odder_q4,overall_q5
0,2017상,서울중부경찰서,75.2,76.5,69.9,65.9,72.6
1,2017상,서울종로경찰서,81.6,82.4,69.1,62.7,72.2
2,2017상,서울남대문경찰서,77.3,79.3,68.8,61.0,71.7
3,2017상,서울서대문경찰서,78.0,80.0,67.0,66.3,71.4
4,2017상,서울혜화경찰서,78.6,80.6,70.7,65.2,75.4
...,...,...,...,...,...,...,...
241,2019하,창원서부경찰서,79.1,79.5,68.5,71.2,76.0
242,2019하,마산중부경찰서,80.8,80.0,70.8,73.2,76.5
243,2019하,마산동부경찰서,75.0,76.5,69.4,68.9,73.1
244,2019하,진주경찰서,78.7,79.6,70.3,74.6,75.6
245,2019하,진해경찰서,76.6,79.2,67.0,70.9,73.5

In [22]:
res.police.nunique(), res.police.unique()

(43,
 array(['서울중부경찰서', '서울종로경찰서', '서울남대문경찰서', '서울서대문경찰서', '서울혜화경찰서', '서울용산경찰서',
        '서울성북경찰서', '서울동대문경찰서', '서울마포경찰서', '서울영등포경찰서', '서울성동경찰서', '서울동작경찰서',
        '서울광진경찰서', '서울서부경찰서', '서울강북경찰서', '서울금천경찰서', '서울중랑경찰서', '서울강남경찰서',
        '서울관악경찰서', '서울강경찰서', '서울강동경찰서', '서울종암경찰서', '서울구로경찰서', '서울서초경찰서',
        '서울양천경찰서', '서울송파경찰서', '서울노원경찰서', '서울방배경찰서', '서울은평경찰서', '서울도봉경찰서',
        '서울수경찰서', '수원중부경찰서', '수원남부경찰서', '수원서부경찰서', '세종경찰서', '창원중부경찰서',
        '창원서부경찰서', '마산중부경찰서', '마산동부경찰서', '진주경찰서', '진해경찰서', '서울강서경찰서',
        '서울수서경찰서'], dtype=object))

In [23]:
res.year.unique()

array(['2017상', '2017하', '2018상', '2018하', '2019상', '2019하'], dtype=object)

In [24]:
res.police = res.police.str.replace( '서울강경찰서','서울강서경찰서')
res.police = res.police.str.replace( '서울수경찰서','서울수서경찰서')

In [25]:
res_pol = res.copy()
res_pol

,year,police,rob_satety_q1,mur_safety_q2,ta_safety_q3,raw_odder_q4,overall_q5
0,2017상,서울중부경찰서,75.2,76.5,69.9,65.9,72.6
1,2017상,서울종로경찰서,81.6,82.4,69.1,62.7,72.2
2,2017상,서울남대문경찰서,77.3,79.3,68.8,61.0,71.7
3,2017상,서울서대문경찰서,78.0,80.0,67.0,66.3,71.4
4,2017상,서울혜화경찰서,78.6,80.6,70.7,65.2,75.4
...,...,...,...,...,...,...,...
241,2019하,창원서부경찰서,79.1,79.5,68.5,71.2,76.0
242,2019하,마산중부경찰서,80.8,80.0,70.8,73.2,76.5
243,2019하,마산동부경찰서,75.0,76.5,69.4,68.9,73.1
244,2019하,진주경찰서,78.7,79.6,70.3,74.6,75.6
245,2019하,진해경찰서,76.6,79.2,67.0,70.9,73.5

## 경찰서명

In [26]:
pol = pd.read_csv('경찰서이름.csv')
pol

        NAME  PNAME
0      세종경찰서    충남청
1      진주경찰서    경남청
2    창원서부경찰서    경남청
3    창원중부경찰서    경남청
4    마산동부경찰서    경남청
5    마산중부경찰서    경남청
6      진해경찰서    경남청
7    서울강동경찰서    서울청
8    서울송파경찰서    서울청
9    서울수서경찰서    서울청
10   서울방배경찰서    서울청
11  서울남대문경찰서    서울청
12   서울서부경찰서    서울청
13   서울양천경찰서    서울청
14   서울강서경찰서    서울청
15   서울성북경찰서    서울청
16   서울용산경찰서    서울청
17   서울광진경찰서    서울청
18   서울종암경찰서    서울청
19   수원남부경찰서  경기남부청
20  서울동대문경찰서    서울청
21   서울성동경찰서    서울청
22   서울중부경찰서    서울청
23   서울혜화경찰서    서울청
24   서울중랑경찰서    서울청
25   서울강남경찰서    서울청
26   서울서초경찰서    서울청
27  서울서대문경찰서    서울청
28   서울종로경찰서    서울청
29   서울마포경찰서    서울청
30   수원서부경찰서  경기남부청
31   수원중부경찰서  경기남부청
32   서울관악경찰서    서울청
33   서울동작경찰서    서울청
34   서울금천경찰서    서울청
35   서울구로경찰서    서울청
36  서울영등포경찰서    서울청
37   서울도봉경찰서    서울청
38   서울은평경찰서    서울청
39   서울강북경찰서    서울청
40   서울노원경찰서    서울청

In [27]:
# 경찰서 이름 확인 
set( pol.NAME ) - set(res_pol.police)

set()

## 전처리데이터

In [31]:
num1 = pd.read_csv('전처리_범죄발생.csv')
num1.rename(columns={'jur_stn':'police'}, inplace=True)
num1

      police   year  범죄발생_절도  범죄발생_폭력  범죄발생_강도  범죄발생_살인  범죄발생_강간/강제추행
0    마산동부경찰서  2017상       61       91        0        0             5
1    마산동부경찰서  2017하       72      102        0        0             6
2    마산동부경찰서  2018상       57       90        0        0             5
3    마산동부경찰서  2018하       72      107        0        0             6
4    마산동부경찰서  2019상       67       97        0        0             7
..       ...    ...      ...      ...      ...      ...           ...
282  창원중부경찰서  2018상       79      112        1        0             8
283  창원중부경찰서  2018하       82      120        1        0             6
284  창원중부경찰서  2019상       93      111        0        0             8
285  창원중부경찰서  2019하       49       88        0        0             7
286  창원중부경찰서   2020       49       88        0        0             7

[287 rows x 7 columns]

In [32]:
num2 = pd.read_csv('전처리_범죄검거.csv')
num2.rename(columns={'jur_stn':'police'}, inplace=True)
num2

      police   year  범죄검거_강간/강제추행  범죄검거_절도  범죄검거_폭력  범죄검거_강도  범죄검거_살인
0    마산동부경찰서  2017상             5       36       82        0        0
1    마산동부경찰서  2017하             5       36       82        0        0
2    마산동부경찰서  2018상             4       40       78        0        0
3    마산동부경찰서  2018하             6       33       93        0        0
4    마산동부경찰서  2019상             6       35       82        0        0
..       ...    ...           ...      ...      ...      ...      ...
282  창원중부경찰서  2018상             6       56      107        1        0
283  창원중부경찰서  2018하             6       52      103        1        0
284  창원중부경찰서  2019상             7       67       99        0        0
285  창원중부경찰서  2019하            11       66      109        0        0
286  창원중부경찰서   2020            11       66      109        0        0

[287 rows x 7 columns]

In [33]:
num3 = pd.read_csv('전처리_교통사고.csv')
num3.rename(columns={'jur_stn':'police'}, inplace=True)
num3

      police   year  acc_case
0    마산동부경찰서  2017상        30
1    마산동부경찰서  2017하        36
2    마산동부경찰서  2018상        34
3    마산동부경찰서  2018하        31
4    마산동부경찰서  2019상        36
..       ...    ...       ...
282  창원중부경찰서  2018상        56
283  창원중부경찰서  2018하        58
284  창원중부경찰서  2019상        52
285  창원중부경찰서  2019하        56
286  창원중부경찰서   2020        46

[287 rows x 3 columns]

In [34]:
num3.year.unique()

array(['2017상', '2017하', '2018상', '2018하', '2019상', '2019하', '2020'],
      dtype=object)

In [35]:
num4 = pd.read_csv('전처리_경찰서_경찰_수.csv')
num4.rename(columns={'pol_office':'police'}, inplace=True)
num4

      police  경찰서 수  경찰 수          면적  경찰서 수/면적    경찰 수/면적
0    마산동부경찰서      7   185   92.338247  0.075808   2.003503
1    마산중부경찰서      8   142  234.700571  0.034086   0.605026
2    서울강남경찰서      8   421   12.164986  0.657625  34.607520
3    서울강동경찰서      9   393   23.446538  0.383852  16.761537
4    서울강북경찰서      9   347   23.693025  0.379859  14.645660
5    서울강서경찰서     10   500   38.298394  0.261108  13.055378
6    서울관악경찰서      9   493   29.568101  0.304382  16.673374
7    서울광진경찰서     10   380   21.902303  0.456573  17.349773
8    서울구로경찰서      8   395   20.123093  0.397553  19.629189
9    서울금천경찰서      5   274   12.951825  0.386046  21.155319
10  서울남대문경찰서      7   186    3.126965  2.238593  59.482604
11   서울노원경찰서      8   415   35.743645  0.223816  11.610456
12   서울도봉경찰서      8   273   20.715537  0.386184  13.178514
13  서울동대문경찰서     11   429   14.391489  0.764341  29.809284
14   서울동작경찰서      7   353   16.255758  0.430617  21.715383
15   서울마포경찰서      8   458   28.699326  0.278752  15.958563
16   서울방배경찰서      4   141    9.245418  0.432647  15.250797
17  서울서대문경찰서      8   322   17.489938  0.457406  18.410586
18   서울서부경찰서      5   221    9.604595  0.520584  23.009819
19   서울서초경찰서      7   339   36.418889  0.192208   9.308356
20   서울성동경찰서      9   320   17.689651  0.508772  18.089672
21   서울성북경찰서      6   252   16.652566  0.360305  15.132803
22   서울송파경찰서     11   538   30.801875  0.357121  17.466469
23   서울수서경찰서      6   312   25.202336  0.238073  12.379805
24   서울양천경찰서      8   376   17.440548  0.458701  21.558955
25  서울영등포경찰서     10   513   19.536493  0.511863  26.258552
26   서울용산경찰서      7   343   25.149995  0.278330  13.638174
27   서울은평경찰서      4   203   20.254969  0.197482  10.022232
28   서울종로경찰서     13   285   18.847568  0.689744  15.121314
29   서울종암경찰서      4   176    7.905105  0.506002  22.264093
30   서울중랑경찰서      8   406   18.453076  0.433532  22.001751
31   서울중부경찰서      7   236    6.821405  1.026182  34.596978
32   서울혜화경찰서      8   213    5.212219  1.534855  40.865514
33     세종경찰서      9   178  465.686315  0.019326   0.382232
34   수원남부경찰서      9   395   41.303676  0.217898   9.563313
35   수원서부경찰서      7   258   38.417692  0.182208   6.715656
36   수원중부경찰서      7   333   40.964180  0.170881   8.129053
37     진주경찰서     13   289  714.142143  0.018204   0.404681
38     진해경찰서      6   137  121.681679  0.049309   1.125888
39   창원서부경찰서      6   155  196.734824  0.030498   0.787863
40   창원중부경찰서      6   201   96.028593  0.062481   2.093127

In [36]:
num5 = pd.read_csv('전처리_112신고.csv')
num5.rename(columns={'jur_stn':'police', '절도/폭력':'신고_절도/폭력', '강도/살인':'신고_강도/살인'}, inplace=True)
num5 = num5[~num5.year.str.contains('2021')]
num5

,police,year,112신고_폭력,112신고_절도,112신고_강도,112신고_살인,112신고_교통사고,112신고_교통불편,112신고_교통위반
0,마산동부경찰서,2017상,261,71,0,0,275,213,27
1,마산동부경찰서,2017하,261,71,0,0,275,213,27
2,마산동부경찰서,2018상,261,71,0,0,275,213,27
3,마산동부경찰서,2018하,258,73,0,0,292,189,40
4,마산동부경찰서,2019상,292,87,0,0,334,208,56
...,...,...,...,...,...,...,...,...,...
322,창원중부경찰서,2018상,280,88,0,0,367,160,46
323,창원중부경찰서,2018하,286,95,0,0,389,144,54
324,창원중부경찰서,2019상,314,110,0,0,450,176,82
325,창원중부경찰서,2019하,305,108,0,0,470,198,102
326,창원중부경찰서,2020,250,105,0,0,427,153,53

In [38]:
num6 = pd.read_csv('전처리_보안등현황.csv')
num6.rename(columns={'경찰서명':'police'}, inplace=True)
num6

      police   year   보안등수
0      세종경찰서  2017상  10410
1      세종경찰서  2017하  10410
2      세종경찰서  2018상  10410
3      세종경찰서  2018하  10410
4      세종경찰서  2019상  10410
..       ...    ...    ...
364  서울노원경찰서  2019상   4078
365  서울노원경찰서  2019하   4078
366  서울노원경찰서  2020상   4078
367  서울노원경찰서  2020하   4078
368  서울노원경찰서  2021상   4078

[369 rows x 3 columns]

In [39]:
num6 =  num6[~num6.year.str.contains('2021')]
num6 = num6[~num6.year.str.contains('2020상')]
num6.year = num6.year.str.replace('2020하', '2020')
num6

      police   year   보안등수
0      세종경찰서  2017상  10410
1      세종경찰서  2017하  10410
2      세종경찰서  2018상  10410
3      세종경찰서  2018하  10410
4      세종경찰서  2019상  10410
..       ...    ...    ...
362  서울노원경찰서  2018상   4078
363  서울노원경찰서  2018하   4078
364  서울노원경찰서  2019상   4078
365  서울노원경찰서  2019하   4078
367  서울노원경찰서   2020   4078

[287 rows x 3 columns]

In [41]:
num7 = pd.read_csv('전처리_공원현황.csv')
num7.rename(columns={'경찰서별':'police'}, inplace=True)
num7

      police  공원현황
0      세종경찰서    88
1      진주경찰서   127
2    창원서부경찰서   140
3    창원중부경찰서   136
4    마산동부경찰서    65
5    마산중부경찰서    55
6      진해경찰서   106
7    서울강동경찰서    72
8    서울송파경찰서   140
9    서울수서경찰서    70
10   서울방배경찰서    25
11  서울남대문경찰서    16
12   서울서부경찰서    46
13   서울양천경찰서    95
14   서울강서경찰서   139
15   서울성북경찰서    29
16   서울용산경찰서    45
17   서울광진경찰서    34
18   서울종암경찰서    22
19   수원남부경찰서   148
20  서울동대문경찰서    14
21   서울성동경찰서    54
22   서울중부경찰서    14
23   서울혜화경찰서    13
24   서울중랑경찰서    54
25   서울강남경찰서    24
26   서울서초경찰서    88
27  서울서대문경찰서    58
28   서울종로경찰서    29
29   서울마포경찰서    82
30   수원서부경찰서   102
31   수원중부경찰서    96
32   서울관악경찰서    78
33   서울동작경찰서    53
34   서울금천경찰서    50
35   서울구로경찰서    45
36  서울영등포경찰서    44
37   서울도봉경찰서    71
38   서울은평경찰서    54
39   서울강북경찰서    41
40   서울노원경찰서   167

In [42]:
num8 = pd.read_csv('전처리_cctv현황.csv')
num8.rename(columns={'경찰서명':'police'}, inplace=True)
num8

      police   year  cctv수
0      세종경찰서  2017상   2527
1      세종경찰서  2017하   2527
2      세종경찰서  2018상   2527
3      세종경찰서  2018하   2527
4      세종경찰서  2019상   2527
..       ...    ...    ...
405  서울노원경찰서  2019하   1998
406  서울노원경찰서  2020상   1998
407  서울노원경찰서  2020하   1998
408  서울노원경찰서  2021상   1998
409  서울노원경찰서  2021하   1998

[410 rows x 3 columns]

In [43]:
num8 =  num8[~num8.year.str.contains('2021')]
num8 = num8[~num8.year.str.contains('2020상')]
num8.year = num8.year.str.replace('2020하', '2020')
num8

      police   year  cctv수
0      세종경찰서  2017상   2527
1      세종경찰서  2017하   2527
2      세종경찰서  2018상   2527
3      세종경찰서  2018하   2527
4      세종경찰서  2019상   2527
..       ...    ...    ...
402  서울노원경찰서  2018상   1624
403  서울노원경찰서  2018하   1741
404  서울노원경찰서  2019상   1953
405  서울노원경찰서  2019하   1998
407  서울노원경찰서   2020   1998

[287 rows x 3 columns]

In [44]:
num8.year.unique()

array(['2017상', '2017하', '2018상', '2018하', '2019상', '2019하', '2020'],
      dtype=object)

In [45]:
num9 = pd.read_csv('전처리_유흥업소현황.csv')
num9.rename(columns={'경찰서명':'police'}, inplace=True)

num9 =  num9[~num9.year.str.contains('2021')]
num9 = num9[~num9.year.str.contains('2020상')]
num9.year = num9.year.str.replace('2020하', '2020')
num9

      police   year  유흥업소수
0      세종경찰서  2017상     62
1      세종경찰서  2017하     63
2      세종경찰서  2018상     63
3      세종경찰서  2018하     65
4      세종경찰서  2019상     66
..       ...    ...    ...
362  서울노원경찰서  2018상     62
363  서울노원경찰서  2018하     63
364  서울노원경찰서  2019상     63
365  서울노원경찰서  2019하     63
367  서울노원경찰서   2020     63

[287 rows x 3 columns]

In [46]:
num10 = pd.read_csv('전처리_외국인인구_경찰서별.csv')
num10

      police   year  외국인인구_계  외국인인구_남자  외국인인구_여자
0    마산동부경찰서  2017상     2770      1635      1135
1    마산동부경찰서  2017하     2770      1624      1146
2    마산동부경찰서  2018상     2770      1614      1156
3    마산동부경찰서  2018하     2820      1612      1208
4    마산동부경찰서  2019상     2871      1611      1260
..       ...    ...      ...       ...       ...
282  창원중부경찰서  2019상     7740      5129      2611
283  창원중부경찰서  2019하     7335      4746      2589
284  창원중부경찰서  2020상     6929      4364      2565
285    세종경찰서  2020상     7244      4398      2846
286    세종경찰서  2019하     7536      4629      2907

[287 rows x 5 columns]

In [47]:
num10[num10.year.str.contains('2020')]
num10.year = num10.year.str.replace( '2020상', '2020')

In [48]:
num11 = pd.read_csv('전처리_기초생활수급자_경찰서별.csv')

num11 = num11[~num11.year.str.contains('2020하')]
num11.year = num11.year.str.replace('2020상', '2020')
num11

      police   year  기초생활수급자
0    마산동부경찰서  2017상     4731
1    마산동부경찰서  2017하     4737
2    마산동부경찰서  2018상     4682
3    마산동부경찰서  2018하     4949
4    마산동부경찰서  2019상     5454
..       ...    ...      ...
322  창원중부경찰서  2018상     7023
323  창원중부경찰서  2018하     7422
324  창원중부경찰서  2019상     8181
325  창원중부경찰서  2019하     8580
326  창원중부경찰서   2020     9192

[287 rows x 3 columns]

In [50]:
num12 = pd.read_csv('전처리_인구분포_경찰서별.csv')
num12 = num12[~num12.year.str.contains('2020하')]
num12.year = num12.year.str.replace('2020상', '2020')

num12

      police   year  popu_female_num  popu_male_num  popu_num
0    마산동부경찰서  2017상           100954         101910    202864
1    마산동부경찰서  2017하            99710         100563    200273
2    마산동부경찰서  2018상            98466          99217    197683
3    마산동부경찰서  2018하            97280          97784    195064
4    마산동부경찰서  2019상            96095          96351    192446
..       ...    ...              ...            ...       ...
282  창원중부경찰서  2018상           169790         182067    351859
283  창원중부경찰서  2018하           168961         180942    349905
284  창원중부경찰서  2019상           168131         179819    347950
285  창원중부경찰서  2019하           168744         178115    346862
286  창원중부경찰서   2020           169360         176414    345774

[287 rows x 5 columns]

In [51]:
num12.year.unique()

array(['2017상', '2017하', '2018상', '2018하', '2019상', '2019하', '2020'],
      dtype=object)

In [52]:
num13 = pd.read_csv('전처리_1인가구_경찰서별.csv')
num13 = num13[~num13.year.str.contains('2020하')]
num13.year = num13.year.str.replace('2020상', '2020')
num13

,police,year,1인가구_10대_계,1인가구_20대_계,1인가구_30대_계,1인가구_40대_계,1인가구_50대_계,1인가구_60대이상_계,1인가구합계_계,1인가구_10대_남자,...,1인가구_50대_남자,1인가구_60대이상_남자,1인가구합계_남자,1인가구_10대_여자,1인가구_20대_여자,1인가구_30대_여자,1인가구_40대_여자,1인가구_50대_여자,1인가구_60대이상_여자,1인가구합계_여자
0,마산동부경찰서,2017상,63,1566,2542,3247,4505,8242,20165,29,...,2381,2735,9818,34,706,820,1156,2124,5507,10347
1,마산동부경찰서,2017하,64,1548,2459,3187,4425,8432,20117,32,...,2355,2818,9778,32,708,791,1123,2070,5614,10338
2,마산동부경찰서,2018상,66,1531,2376,3128,4346,8622,20069,36,...,2330,2901,9739,30,710,762,1091,2016,5721,10330
3,마산동부경찰서,2018하,73,1557,2292,3010,4307,8960,20200,37,...,2331,3017,9713,36,738,745,1047,1976,5943,10486
4,마산동부경찰서,2019상,81,1583,2208,2892,4268,9299,20331,39,...,2332,3133,9688,42,767,729,1003,1936,6166,10643
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
282,창원중부경찰서,2018상,99,4915,7091,6369,6391,8006,32874,50,...,3331,2758,17723,49,2055,2326,2414,3059,5247,15151
283,창원중부경찰서,2018하,105,5151,7026,6360,6527,8353,33528,55,...,3401,2881,17973,49,2163,2316,2425,3124,5470,15552
284,창원중부경찰서,2019상,112,5388,6960,6350,6664,8703,34179,61,...,3474,3006,18225,51,2273,2305,2437,3190,5695,15954
285,창원중부경찰서,2019하,110,5743,7209,6447,6827,9276,35616,59,...,3606,3223,19038,49,2450,2336,2463,3220,6051,16576
286,창원중부경찰서,2020,111,6098,7460,6544,6990,9849,37053,58,...,3739,3439,19852,50,2628,2370,2489,3251,6409,17201

## 데이터 머지

In [53]:
_ = pd.merge( num1, num2, on=['police', 'year'], how='outer')
_ = pd.merge( _, num3, on=['police', 'year'], how='outer')
_ = pd.merge( _, num4, on=['police'], how='outer')
_ = pd.merge( _, num5, on=['police', 'year'], how='outer')
_ = pd.merge( _, num6, on=['police', 'year'], how='outer')
_ = pd.merge( _, num7, on=['police'], how='outer')
_ = pd.merge( _, num8, on=['police', 'year'], how='outer')
_ = pd.merge( _, num9, on=['police', 'year'], how='outer')
_ = pd.merge( _, num10, on=['police', 'year'], how='outer')
_ = pd.merge( _, num11, on=['police', 'year'], how='outer')
_ = pd.merge( _, num12, on=['police', 'year'], how='outer')
_ = pd.merge( _, num13, on=['police', 'year'], how='outer')
_

,police,year,범죄발생_절도,범죄발생_폭력,범죄발생_강도,범죄발생_살인,범죄발생_강간/강제추행,범죄검거_강간/강제추행,범죄검거_절도,범죄검거_폭력,...,1인가구_50대_남자,1인가구_60대이상_남자,1인가구합계_남자,1인가구_10대_여자,1인가구_20대_여자,1인가구_30대_여자,1인가구_40대_여자,1인가구_50대_여자,1인가구_60대이상_여자,1인가구합계_여자
0,마산동부경찰서,2017상,61,91,0,0,5,5,36,82,...,2381,2735,9818,34,706,820,1156,2124,5507,10347
1,마산동부경찰서,2017하,72,102,0,0,6,5,36,82,...,2355,2818,9778,32,708,791,1123,2070,5614,10338
2,마산동부경찰서,2018상,57,90,0,0,5,4,40,78,...,2330,2901,9739,30,710,762,1091,2016,5721,10330
3,마산동부경찰서,2018하,72,107,0,0,6,6,33,93,...,2331,3017,9713,36,738,745,1047,1976,5943,10486
4,마산동부경찰서,2019상,67,97,0,0,7,6,35,82,...,2332,3133,9688,42,767,729,1003,1936,6166,10643
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
282,창원중부경찰서,2018상,79,112,1,0,8,6,56,107,...,3331,2758,17723,49,2055,2326,2414,3059,5247,15151
283,창원중부경찰서,2018하,82,120,1,0,6,6,52,103,...,3401,2881,17973,49,2163,2316,2425,3124,5470,15552
284,창원중부경찰서,2019상,93,111,0,0,8,7,67,99,...,3474,3006,18225,51,2273,2305,2437,3190,5695,15954
285,창원중부경찰서,2019하,49,88,0,0,7,11,66,109,...,3606,3223,19038,49,2450,2336,2463,3220,6051,16576
286,창원중부경찰서,2020,49,88,0,0,7,11,66,109,...,3739,3439,19852,50,2628,2370,2489,3251,6409,17201

In [54]:
_.groupby(['police','year']).sum()

               범죄발생_절도  범죄발생_폭력  범죄발생_강도  범죄발생_살인  범죄발생_강간/강제추행  범죄검거_강간/강제추행  \
police  year
마산동부경찰서 2017상       61       91        0        0             5             5
        2017하       72      102        0        0             6             5
        2018상       57       90        0        0             5             4
        2018하       72      107        0        0             6             6
        2019상       67       97        0        0             7             6
...                ...      ...      ...      ...           ...           ...
창원중부경찰서 2018상       79      112        1        0             8             6
        2018하       82      120        1        0             6             6
        2019상       93      111        0        0             8             7
        2019하       49       88        0        0             7            11
        2020        49       88        0        0             7            11

               범죄검거_절도  범죄검거_폭력  범죄검거_강도  범죄검거_살인  ...  1인가구_50대_남자  \
police  year                                       ...
마산동부경찰서 2017상       36       82        0        0  ...         2381
        2017하       36       82        0        0  ...         2355
        2018상       40       78        0        0  ...         2330
        2018하       33       93        0        0  ...         2331
        2019상       35       82        0        0  ...         2332
...                ...      ...      ...      ...  ...          ...
창원중부경찰서 2018상       56      107        1        0  ...         3331
        2018하       52      103        1        0  ...         3401
        2019상       67       99        0        0  ...         3474
        2019하       66      109        0        0  ...         3606
        2020        66      109        0        0  ...         3739

               1인가구_60대이상_남자  1인가구합계_남자  1인가구_10대_여자  1인가구_20대_여자  \
police  year
마산동부경찰서 2017상           2735       9818           34          706
        2017하           2818       9778           32          708
        2018상           2901       9739           30          710
        2018하           3017       9713           36          738
        2019상           3133       9688           42          767
...                      ...        ...          ...          ...
창원중부경찰서 2018상           2758      17723           49         2055
        2018하           2881      17973           49         2163
        2019상           3006      18225           51         2273
        2019하           3223      19038           49         2450
        2020            3439      19852           50         2628

               1인가구_30대_여자  1인가구_40대_여자  1인가구_50대_여자  1인가구_60대이상_여자  1인가구합계_여자
police  year
마산동부경찰서 2017상          820         1156         2124           5507      10347
        2017하          791         1123         2070           5614      10338
        2018상          762         1091         2016           5721      10330
        2018하          745         1047         1976           5943      10486
        2019상          729         1003         1936           6166      10643
...                    ...          ...          ...            ...        ...
창원중부경찰서 2018상         2326         2414         3059           5247      15151
        2018하         2316         2425         3124           5470      15552
        2019상         2305         2437         3190           5695      15954
        2019하         2336         2463         3220           6051      16576
        2020          2370         2489         3251           6409      17201

[287 rows x 55 columns]

In [55]:
df_new = pd.merge( _, res_pol , on=['police', 'year'], how='outer')
df_new

,police,year,범죄발생_절도,범죄발생_폭력,범죄발생_강도,범죄발생_살인,범죄발생_강간/강제추행,범죄검거_강간/강제추행,범죄검거_절도,범죄검거_폭력,...,1인가구_30대_여자,1인가구_40대_여자,1인가구_50대_여자,1인가구_60대이상_여자,1인가구합계_여자,rob_satety_q1,mur_safety_q2,ta_safety_q3,raw_odder_q4,overall_q5
0,마산동부경찰서,2017상,61,91,0,0,5,5,36,82,...,820,1156,2124,5507,10347,74.6,77.0,64.0,65.7,71.2
1,마산동부경찰서,2017하,72,102,0,0,6,5,36,82,...,791,1123,2070,5614,10338,71.7,73.5,64.9,63.6,70.3
2,마산동부경찰서,2018상,57,90,0,0,5,4,40,78,...,762,1091,2016,5721,10330,76.0,79.0,67.5,70.0,72.6
3,마산동부경찰서,2018하,72,107,0,0,6,6,33,93,...,745,1047,1976,5943,10486,72.4,75.6,67.9,70.7,71.8
4,마산동부경찰서,2019상,67,97,0,0,7,6,35,82,...,729,1003,1936,6166,10643,76.1,78.2,66.4,69.9,72.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
282,창원중부경찰서,2018상,79,112,1,0,8,6,56,107,...,2326,2414,3059,5247,15151,78.0,80.1,65.3,68.6,72.9
283,창원중부경찰서,2018하,82,120,1,0,6,6,52,103,...,2316,2425,3124,5470,15552,75.7,77.7,67.8,70.6,74.2
284,창원중부경찰서,2019상,93,111,0,0,8,7,67,99,...,2305,2437,3190,5695,15954,80.8,82.8,69.4,73.8,76.1
285,창원중부경찰서,2019하,49,88,0,0,7,11,66,109,...,2336,2463,3220,6051,16576,77.6,79.6,70.9,73.6,74.1
286,창원중부경찰서,2020,49,88,0,0,7,11,66,109,...,2370,2489,3251,6409,17201,NaN,NaN,NaN,NaN,NaN

In [56]:
# 년도를 범주형->이산형 데이터로 인코딩해준다.
from sklearn.preprocessing import LabelEncoder
# data = df.copy() 
data = df_new.copy() 

cols = [ 'year'] 
for c in cols:
    lbl = LabelEncoder() 
    lbl.fit(list(data[c].values)) 
    data[c] = lbl.transform(list(data[c].values))

## 저장

In [277]:
# data.to_csv('temp_data.csv', header=True, index=False, encoding='utf-8-sig')